.github/workflows/release.yml

- pins python-semantic-release action

chore: pins python-semantic-release action

---

README.md

- removes get_decrypted and list_decrypted from tokens api

feat: removes get_decrypted and list_decrypted from tokens api

---

scripts/integrationtests.sh

- updating integration tests sh file

chore: updating integration tests sh file

---

integration-tests/test_applications.py
integration-tests/test_logs.py
integration-tests/test_permissions.py
integration-tests/test_reactor_formulas.py
integration-tests/test_reactors.py
integration-tests/test_tenants.py
integration-tests/test_tokenize.py
integration-tests/test_tokens.py

- Assert permission count > 0 in integration tests
- Linting

chore: assert permission count > 0, lint integration tests [ci skip]

---

.openapi-generator-ignore
setup.cfg

- Adds back semantic release configuration that got removed on code regeneration

fix: fix semantic release

---

.openapi-generator/FILES
basistheory/model/create_proxy_request.py
basistheory/model/create_token_request.py
basistheory/model/proxy.py
basistheory/model/tenant.py
basistheory/model/update_proxy_request.py
basistheory/model/update_tenant_request.py

- Add deduplicate token setting to tenants and token requests
- Return tenant settings on tenant endpoints
- Add response reactor id to proxy

feat: add deduplicate token settings

---

.openapi-generator/FILES
basistheory/model/create_token_request.py
basistheory/model/create_token_response.py
basistheory/model/token.py
basistheory/model/update_token_request.py
integration-tests/test_tokens.py

- Add mask to create and update token request and response

feat: adding mask property to tokens api

---

integration-tests/test_tokens.py

- Fix token updating mask integration test

chore: fix integration test

---

basistheory/model/atomic_bank.py
basistheory/model/atomic_card.py
basistheory/model/create_token_request.py
basistheory/model/create_token_response.py
basistheory/model/token.py
integration-tests/test_logs.py

- Add token id to the create token request

feat: adding token id to the create token request

---

.github/workflows/pull-request.yml
.openapi-generator/FILES
basistheory/api/banks_api.py
basistheory/api/cards_api.py
basistheory/api/proxies_api.py
basistheory/api/reactor_formulas_api.py
basistheory/api/reactors_api.py
basistheory/api/tenants_api.py
basistheory/api/tokens_api.py
basistheory/models/__init__.py
integration-tests/pytest.ini.example
integration-tests/test_reactors.py

- BREAKING CHANGE: remove `react` methods on atomic cards and banks
- Fix issue where some parameters were marked as not required (create/update bodies).

refactor: remove atomic react methods, fix required params

---

.github/workflows/pull-request.yml
integration-tests/pytest.ini.example
integration-tests/test_reactors.py

- Reads card reactor ID from environment variable, remove hard-coded ID

ci: read card reactor id from BT_CARD_REACTOR_ID env variable [ci skip]

---

templates/configuration.mustache

- Disables client side validation generated from swagger spec by default

chore: disable client validation by default

---

.github/workflows/release.yml

- Bumps semantic release action back to `master`

fix: bump semantic release action

---

setup.cfg

- Marks `tag` as the version source for current release.

fix: fix semantic release version source

---

README.md

- Attempt to trigger a release based on tag.

feat: add token expires_at, validations, updated models

---

integration-tests/test_applications.py

- Providing permissions when updating applications in integration tests

chore: fixing failing integration test

---

integration-tests/test_applications.py

- Updates failing integration tests

chore: Updates permissions referenced from integration tests

---

CONTRIBUTING.md
integration-tests/test_applications.py
integration-tests/test_logs.py
integration-tests/test_permissions.py
integration-tests/test_reactor_formulas.py
integration-tests/test_reactors.py
integration-tests/test_tenants.py
integration-tests/test_tokenize.py
integration-tests/test_tokens.py

dev domain work

---

.openapi-generator/FILES
basistheory/model/create_reactor_request.py
basistheory/model/patch_reactor_request.py
basistheory/model/proxy.py
basistheory/model/reactor.py
basistheory/model/token_report.py
basistheory/model/update_reactor_request.py
basistheory/models/__init__.py
swagger.json

feat: remove MATs from token report, add code to reactors

---

integration-tests/test_logs.py

fix: fixing integration test

---

integration-tests/test_tokens.py

- Disabling search integration test so we can better re-adapt it to account for replication lag in our CI.

chore: disable search integration test
